codecov:
  CODECOV_TOKEN: ad91dc9f-f0c6-464c-bd8c-09369006c858 
  require_ci_to_pass: yes
 
 coverage:
  status:
    project:
      default:
        informational: true
    patch:
       default:
        informational: true
    
