version: 2.1
orbs:
  codecov: codecov/codecov@1.1.0

jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test 
      - run: flutter build apk --release
      - run:
          name: Upload coverage report to Codecov
          command: codecov/upload
      - store_artifacts:
            path: build/app/outputs/flutter-apk/app-release.apk
      - store_test_results:
            path: test-results
            
