version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4
  flutter: circleci/flutter@2.0.0

jobs:
  build:
    environment:
      CODECOV_TOKEN: "ad91dc9f-f0c6-464c-bd8c-09369006c858"
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.0.3
      - run: flutter test --coverage
      - run: flutter pub get
      - run: flutter build web
      - run: flutter build apk --release

      - store_artifacts:
            path: build/app/outputs/flutter-apk/app-release.apk
      - store_test_results:
            path: test-results change this code so it runs the web app
