version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build:
    environment:
      CODECOV_TOKEN: "ad91dc9f-f0c6-464c-bd8c-09369006c858"
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test --coverage
      - run: flutter pub get
      - run: flutter build web
      - run: xdg-open https://quiz-database-3b25e.web.app
      - store_artifacts:
            path: build/web/
      - store_test_results:
            path: test-results
workflows:
  build:
    jobs:
      - build
