// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtgHTASmgmpNeBHfg8pS-q1UfrgpvpENs',
    appId: '1:238968611576:web:b890c82befa2efccd5510d',
    messagingSenderId: '238968611576',
    projectId: 'quiz-database-3b25e',
    authDomain: 'quiz-database-3b25e.firebaseapp.com',
    databaseURL: 'https://quiz-database-3b25e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-database-3b25e.appspot.com',
    measurementId: 'G-KP43WM7YBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAULbfSRzAOm3x56gaUIuXMzF1SnyNBQ7o',
    appId: '1:238968611576:android:c0619d503d00faddd5510d',
    messagingSenderId: '238968611576',
    projectId: 'quiz-database-3b25e',
    databaseURL: 'https://quiz-database-3b25e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-database-3b25e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfZ5qUlZRI2TvNXy0R5W8S4ww1t7nFkNM',
    appId: '1:238968611576:ios:eb9d4036add3d2dfd5510d',
    messagingSenderId: '238968611576',
    projectId: 'quiz-database-3b25e',
    databaseURL: 'https://quiz-database-3b25e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-database-3b25e.appspot.com',
    iosClientId: '238968611576-ss11fv7stteqlh09tk8b18ctkrtlt2cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfZ5qUlZRI2TvNXy0R5W8S4ww1t7nFkNM',
    appId: '1:238968611576:ios:eb9d4036add3d2dfd5510d',
    messagingSenderId: '238968611576',
    projectId: 'quiz-database-3b25e',
    databaseURL: 'https://quiz-database-3b25e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-database-3b25e.appspot.com',
    iosClientId: '238968611576-ss11fv7stteqlh09tk8b18ctkrtlt2cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizWebsite',
  );
}
